spring:
  application:
    name: file-storage-s3
  main:
    web-application-type: reactive
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/filestorage?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8}
    username: ${SPRING_DATASOURCE_USERNAME:fs_user}
    password: ${SPRING_DATASOURCE_PASSWORD:fs_pass_123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  codec:
    multipart:
      enabled: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:dev-secret-change-me-please-at-least-32-bytes}
  expiresMinutes: ${JWT_EXPIRES_MINUTES:120}

# S3/MinIO
s3:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  accessKey: ${S3_ACCESS_KEY:minioadmin}
  secretKey: ${S3_SECRET_KEY:minioadmin123}
  region: ${S3_REGION:us-east-1}
  bucket: ${S3_BUCKET:file-storage}
  publicBaseUrl: ${S3_PUBLIC_BASE_URL:http://localhost:9000}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/filestorage?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        probes:
          enabled: true
        show-details: never

